sh run_snort.sh malware-cnc.rules
sh run_snort.sh browser-plugins.rules
sh run_snort.sh blacklist.rules
sh run_snort.sh browser-ie.rules
sh run_snort.sh file-flash.rules
sh run_snort.sh server-webapp.rules
sh run_snort.sh file-office.rules
sh run_snort.sh server-other.rules
sh run_snort.sh os-windows.rules
sh run_snort.sh file-identify.rules
sh run_snort.sh file-other.rules
sh run_snort.sh file-pdf.rules
sh run_snort.sh exploit-kit.rules
sh run_snort.sh pua-adware.rules
sh run_snort.sh malware-other.rules
sh run_snort.sh malware-backdoor.rules
sh run_snort.sh server-oracle.rules
sh run_snort.sh file-multimedia.rules
sh run_snort.sh file-image.rules
sh run_snort.sh netbios.rules
sh run_snort.sh file-java.rules
sh run_snort.sh indicator-compromise.rules
sh run_snort.sh browser-firefox.rules
sh run_snort.sh protocol-voip.rules
sh run_snort.sh protocol-scada.rules
sh run_snort.sh protocol-rpc.rules
sh run_snort.sh pua-toolbars.rules
sh run_snort.sh indicator-shellcode.rules
sh run_snort.sh indicator-obfuscation.rules
sh run_snort.sh policy-other.rules
sh run_snort.sh server-iis.rules
sh run_snort.sh server-mail.rules
sh run_snort.sh policy-spam.rules
sh run_snort.sh malware-tools.rules
sh run_snort.sh app-detect.rules
sh run_snort.sh os-mobile.rules
sh run_snort.sh server-apache.rules
sh run_snort.sh protocol-ftp.rules
sh run_snort.sh sql.rules
sh run_snort.sh browser-webkit.rules
sh run_snort.sh protocol-icmp.rules
sh run_snort.sh file-executable.rules
sh run_snort.sh server-mysql.rules
sh run_snort.sh server-mssql.rules
sh run_snort.sh protocol-dns.rules
sh run_snort.sh policy-social.rules
sh run_snort.sh browser-other.rules
sh run_snort.sh protocol-imap.rules
sh run_snort.sh browser-chrome.rules
sh run_snort.sh os-other.rules
sh run_snort.sh protocol-snmp.rules
sh run_snort.sh server-samba.rules
sh run_snort.sh os-linux.rules
sh run_snort.sh protocol-telnet.rules
sh run_snort.sh indicator-scan.rules
sh run_snort.sh pua-other.rules
sh run_snort.sh protocol-pop.rules
sh run_snort.sh protocol-tftp.rules
sh run_snort.sh pua-p2p.rules
sh run_snort.sh content-replace.rules
sh run_snort.sh protocol-services.rules
sh run_snort.sh protocol-nntp.rules
sh run_snort.sh os-solaris.rules
sh run_snort.sh protocol-finger.rules
sh run_snort.sh policy-multimedia.rules
sh run_snort.sh x11.rules
sh run_snort.sh scada.rules
